id: yaml-poc-redhat-jboss_enterprise_application_platform-logical-CVE-2017-7504
info:
  name: Yaml Poc Redhat Jboss_Enterprise_Application_Platform Logical Cve 2017 7504
  author: converted
  severity: critical
  description: 'Converted from xpoc: yaml-poc-redhat-jboss_enterprise_application_platform-logical-CVE-2017-7504'
  tags: cve
  classification:
    cve-id: CVE-2017-7504
  reference:
  - http://www.securityfocus.com/bid/98595
  - https://bugzilla.redhat.com/show_bug.cgi?id=1451441
  - https://nvd.nist.gov/vuln/detail/CVE-2017-7504
  - https://www.securityfocus.com/bid/98595
http:
- method: POST
  path:
  - /jbossmq-httpil/HTTPServerILServlet
  body: any
  headers:
    Content-Type: application/x-www-form-urlencoded
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    part: body
    words:
    - org.jboss.mq.il.http.servlet
