id: yaml-poc-redhat-jboss_enterprise_application_platform-logical-CVE-2015-7501
info:
  name: Yaml Poc Redhat Jboss_Enterprise_Application_Platform Logical Cve 2015 7501
  author: converted
  severity: critical
  description: 'Converted from xpoc: yaml-poc-redhat-jboss_enterprise_application_platform-logical-CVE-2015-7501'
  tags: cve
  classification:
    cve-id: CVE-2015-7501
  reference:
  - http://rhn.redhat.com/errata/RHSA-2015-2500.html
  - http://rhn.redhat.com/errata/RHSA-2015-2501.html
  - http://rhn.redhat.com/errata/RHSA-2015-2502.html
  - http://rhn.redhat.com/errata/RHSA-2015-2514.html
  - http://rhn.redhat.com/errata/RHSA-2015-2516.html
http:
- method: GET
  path:
  - /invoker/JMXInvokerServlet
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    part: body
    words:
    - MarshalledValue
