id: yaml-poc-citrix-application_delivery_controller-leak-CVE-2023-4966
info:
  name: Yaml Poc Citrix Application_Delivery_Controller Leak Cve 2023 4966
  author: yuxiang.cai
  severity: high
  description: 'Converted from xpoc: yaml-poc-citrix-application_delivery_controller-leak-CVE-2023-4966'
  tags: citrix,cve
  classification:
    cve-id: CVE-2023-4966
  reference:
  - http://packetstormsecurity.com/files/175323/Citrix-Bleed-Session-Token-Leakage-Proof-Of-Concept.html
  - https://support.citrix.com/article/CTX579459
http:
- method: GET
  path:
  - /oauth/idp/.well-known/openid-configuration
  headers:
    Connection: close
    Host: '{{host}}'
