id: yaml-poc-redhat-jboss_enterprise_application_platform-unauthorized_access-CVE-2017-12149
info:
  name: Yaml Poc Redhat Jboss_Enterprise_Application_Platform Unauthorized_Access
    Cve 2017 12149
  author: converted
  severity: critical
  description: 'Converted from xpoc: yaml-poc-redhat-jboss_enterprise_application_platform-unauthorized_access-CVE-2017-12149'
  tags: unauth,cve
  classification:
    cve-id: CVE-2017-12149
  reference:
  - http://www.securityfocus.com/bid/100591
  - https://access.redhat.com/errata/RHSA-2018:1607
  - https://access.redhat.com/errata/RHSA-2018:1608
  - https://bugzilla.redhat.com/show_bug.cgi?id=1486220
  - https://github.com/gottburgm/Exploits/tree/master/CVE-2017-12149
http:
- method: GET
  path:
  - /invoker/readonly
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 500
  - type: word
    part: body
    words:
    - EOFExeption
    - ReadOnlyAccessFilter.java
